### ISSUE TITLE
Add count query option

### ISSUE THREAD

**Issue by mtejedorwolox** [Wolox/wor-paginate#77]
Allow to receive a `count_query` option to render_paginated

**Comment by joredudiaz** [comment]
What do you want to count with this `count_query` option? Isn't similar to `limit`? can you clarify this please? @mtejedorwolox @mnmallea

**Comment by mtejedorwolox** [comment]
The idea here is to use it like this
`render_paginated complex_query, count_query: complex_count_query`
at this moment the count query makes a `SELECT COUNT(wrapped query)` and this brokes when you have a query that uses a custom select, if i could have this parameter it will be easy for me to do: `render_paginated complex_query, count_query: complex_query.count('my conditions or columns to count')`

**Comment by joredudiaz** [comment]
I'm doing the next query `Banner.select('name,bannerable_id,bannerable_type')`; with 1.6 gem's version raise the error that you said, but at version 1.8 does not, because in this version it uses `size` function to count the records not `count` (and you know that size does not execute a SQL query to count the records). So the `count_query` would be unnecessary. Can you give more information to reproduce the error in the current version (1.10), like adapter, formatter or anything else. 😄 Thank you!.

**Comment by mnmallea** [comment]
I think we could add `count_query` as an optional parameter anyway. Because in this way we are covered about another edge case that could break the pagination.
